version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgre_container
    environment:
      POSTGRES_USER:postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    container_name: my_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
    ports:
      - "3000:3000"
volumes:
  pgdata: